# 02-2: RNN vanilla 

## Implementar basic RNN cell

In [5]:
import numpy as np

# TODO: Implement softmax

def rnn_cell_forward(xt, a_prev, parameters):
    
    # Retrieve parameters from "parameters"
    Wax = parameters["Wax"]
    Waa = parameters["Waa"]
    Wya = parameters["Wya"]
    ba = parameters["ba"]
    by = parameters["by"]
    
    # TODO: Compute next activation state a_next
    
    # TODO: Compute output of the current cell
        
    # store values you need for backward propagation in cache
    cache = (a_next, a_prev, xt, parameters)
    
    return a_next, yt_pred, cache

In [7]:
np.random.seed(1)
xt_tmp = np.random.randn(3, 10)  # batch, dim
a_prev_tmp = np.random.randn(5, 10)
parameters_tmp = {}
parameters_tmp['Waa'] = np.random.randn(5, 5)
parameters_tmp['Wax'] = np.random.randn(5, 3)
parameters_tmp['Wya'] = np.random.randn(2, 5)
parameters_tmp['ba'] = np.random.randn(5, 1)
parameters_tmp['by'] = np.random.randn(2, 1)

a_next_tmp, yt_pred_tmp, cache_tmp = rnn_cell_forward(xt_tmp, a_prev_tmp, parameters_tmp)
print("a_next[4] = \n", a_next_tmp[4])
print("a_next.shape = \n", a_next_tmp.shape)
print("yt_pred[1] =\n", yt_pred_tmp[1])
print("yt_pred.shape = \n", yt_pred_tmp.shape)


a_next[4] = 
 [ 0.59584544  0.18141802  0.61311866  0.99808218  0.85016201  0.99980978
 -0.18887155  0.99815551  0.6531151   0.82872037]
a_next.shape = 
 (5, 10)
yt_pred[1] =
 [0.19872856 0.00066249 0.00214437 0.00257758 0.0441077  0.00921221
 0.01102142 0.23530417 0.48830784 0.00793366]
yt_pred.shape = 
 (2, 10)


## Forward prop

In [8]:
def rnn_forward(x, a0, parameters):
    """
    Implement the forward propagation of the recurrent neural network described in Figure (3).

    Arguments:
    x -- Input data for every time-step, of shape (n_x, m, T_x).
    a0 -- Initial hidden state, of shape (n_a, m)
    parameters -- python dictionary containing:
                        Waa -- Weight matrix multiplying the hidden state, numpy array of shape (n_a, n_a)
                        Wax -- Weight matrix multiplying the input, numpy array of shape (n_a, n_x)
                        Wya -- Weight matrix relating the hidden-state to the output, numpy array of shape (n_y, n_a)
                        ba --  Bias numpy array of shape (n_a, 1)
                        by -- Bias relating the hidden-state to the output, numpy array of shape (n_y, 1)

    Returns:
    a -- Hidden states for every time-step, numpy array of shape (n_a, m, T_x)
    y_pred -- Predictions for every time-step, numpy array of shape (n_y, m, T_x)
    caches -- tuple of values needed for the backward pass, contains (list of caches, x)
    """
    
    # Initialize "caches" which will contain the list of all caches
    caches = []
    
    # Retrieve dimensions from shapes of x and parameters["Wya"]
    n_x, m, T_x = x.shape
    n_y, n_a = parameters["Wya"].shape
    
    ### START CODE HERE ###
    
    # initialize "a" and "y_pred" with zeros (≈2 lines)
    a = np.zeros((n_a, m, T_x))
    y_pred = np.zeros((n_y, m, T_x))
    
    # Initialize a_next (≈1 line)
    a_next = a0
    
    # loop over all time-steps
    for t in range(T_x):
        # Update next hidden state, compute the prediction, get the cache (≈1 line)
        a_next, yt_pred, cache = rnn_cell_forward(x[:,:,t], a_next, parameters)
        # Save the value of the new "next" hidden state in a (≈1 line)
        a[:,:,t] = a_next
        # Save the value of the prediction in y (≈1 line)
        y_pred[:,:,t] = yt_pred
        # Append "cache" to "caches" (≈1 line)
        caches.append(cache)
    ### END CODE HERE ###
    
    # store values needed for backward propagation in cache
    caches = (caches, x)
    
    return a, y_pred, caches

## Ejecutar

In [10]:
np.random.seed(1)
x_tmp = np.random.randn(3, 10, 4)  # batch, timesteps, dim
a0_tmp = np.random.randn(5, 10)
parameters_tmp = {}
parameters_tmp['Waa'] = np.random.randn(5, 5)
parameters_tmp['Wax'] = np.random.randn(5, 3)
parameters_tmp['Wya'] = np.random.randn(2, 5)
parameters_tmp['ba'] = np.random.randn(5, 1)
parameters_tmp['by'] = np.random.randn(2, 1)

a_tmp, y_pred_tmp, caches_tmp = rnn_forward(x_tmp, a0_tmp, parameters_tmp)
print("a[4][1] = \n", a_tmp[4][1])
print("a.shape = \n", a_tmp.shape)
print("y_pred[1][3] =\n", y_pred_tmp[1][3])
print("y_pred.shape = \n", y_pred_tmp.shape)
print("caches[1][1][3] =\n", caches_tmp[1][1][3])
print("len(caches) = \n", len(caches_tmp))

#UNIT TEST    
#rnn_forward_test(rnn_forward)

a[4][1] = 
 [-0.99999375  0.77911235 -0.99861469 -0.99833267]
a.shape = 
 (5, 10, 4)
y_pred[1][3] =
 [0.26132748 0.20856782 0.02925052 0.15841612]
y_pred.shape = 
 (2, 10, 4)
caches[1][1][3] =
 [-1.1425182  -0.34934272 -0.20889423  0.58662319]
len(caches) = 
 2


## Mejor con keras.layers.SimpleRNN

In [16]:
# create and fit the SimpleRNN model

import keras
import numpy as np
inputs = np.random.random((3, 10, 4)) #  # batch, timesteps, dim
simple_rnn = keras.layers.SimpleRNN(4)
output = simple_rnn(inputs)  # The output has shape `(32, 4)`.
print(output.shape)
simple_rnn = keras.layers.SimpleRNN(
    4, return_sequences=True, return_state=True
)
# whole_sequence_output has shape `(32, 10, 4)`.
# final_state has shape `(32, 4)`.
whole_sequence_output, final_state = simple_rnn(inputs)
print(whole_sequence_output.shape)
print(final_state)


(3, 4)
(3, 10, 4)
tf.Tensor(
[[-0.16965559  0.17795296 -0.4662523   0.60001403]
 [ 0.5581392  -0.5770083   0.1915477   0.78707093]
 [ 0.6415554  -0.46975076  0.19463192  0.08864395]], shape=(3, 4), dtype=float32)


In [14]:
print(inputs)

[[[0.36179576 0.9853168  0.86877887 0.15249674]
  [0.79882609 0.81099692 0.92820722 0.22438427]
  [0.49896747 0.82744409 0.66733378 0.59393614]
  [0.65197582 0.23851601 0.02554008 0.73625726]
  [0.32679183 0.37675689 0.61261605 0.65716504]
  [0.2028989  0.82603154 0.38020661 0.63174441]
  [0.96641142 0.56478624 0.35891114 0.61897011]
  [0.50179312 0.45237625 0.73227073 0.92451015]
  [0.47927142 0.08823015 0.56965356 0.24495086]
  [0.03957791 0.78814021 0.27276824 0.77707049]]

 [[0.48820894 0.31793589 0.31402545 0.04202476]
  [0.53439984 0.82355156 0.08389535 0.10855871]
  [0.52925593 0.66014181 0.69474599 0.3132217 ]
  [0.03777778 0.41456288 0.22604417 0.00111483]
  [0.68571657 0.95206254 0.39115176 0.30029843]
  [0.55375181 0.85197626 0.79496742 0.6847567 ]
  [0.43210709 0.69043402 0.21602535 0.28394344]
  [0.77782061 0.92998014 0.1900495  0.29606329]
  [0.00621027 0.43156225 0.21029507 0.64142478]
  [0.70958922 0.11877771 0.082144   0.90633507]]

 [[0.38923875 0.5334035  0.96324156 

In [4]:
print(final_state)

tf.Tensor(
[[-0.03179753  0.14509289  0.9781907   0.5019735 ]
 [-0.11994798  0.43354037  0.97148097  0.32557377]
 [-0.4176154   0.40960777  0.8407844   0.70254743]
 [-0.7159653  -0.02250117  0.9023634   0.76640546]
 [ 0.12313093  0.0898631   0.97702044  0.07784285]
 [-0.00291277  0.24100319  0.98433566  0.47263044]
 [-0.6475453   0.13773736  0.95074046  0.7057345 ]
 [-0.8395195  -0.19906163  0.95005447  0.83500016]
 [-0.395829   -0.3478586   0.9977278  -0.21805848]
 [-0.01188049  0.5154062   0.96507686  0.03526821]
 [-0.21965803  0.28714785  0.972595    0.69383097]
 [-0.01700303  0.33022204  0.5891278   0.837763  ]
 [ 0.06305152  0.68379706  0.9436949   0.6681444 ]
 [-0.66979027 -0.2088745   0.9639633   0.65318435]
 [-0.3409407  -0.53009117  0.9732123   0.6929266 ]
 [-0.50739     0.03619301  0.98472357  0.5786426 ]
 [-0.68411213 -0.30439126  0.93527174  0.8397238 ]
 [-0.24298665  0.55986184  0.69763476  0.62231386]
 [-0.5486438  -0.3135246   0.97548276  0.73780507]
 [-0.29320362  0.063